# datasets: [cuad, techqa] # covidqa, hagrid, hotpotqa, emanual, msmarco, pubmedqa, delucionqa, expertqa
datasets: [conditionalqa, cuad, qasper, techqa]
chunkers: [BaseChunker, SingleLinkageChunker, DBSCANChunker, LangchainChunker, AbsoluteLangchainChunker, PositionalChunker]

# add hyperparameter configs below for your own chunker
PositionalChunker:
  n_chunks: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  n_sents_overlap: [0, 1]

SingleLinkageChunker:
  lamda: [0, 0.25, 0.5, 0.75, 1]
  n_clusters: [2, 3, 4, 5, 6, 7, 8, 9, 10]

DBSCANChunker:
  lamda: [0, 0.25, 0.5, 0.75, 1]
  eps: [0.1, 0.2, 0.3, 0.4, 0.5]
  min_samples_per_cluster: [1, 2, 3, 4, 5]

LangchainChunker:
  breakpoint_threshold_type: [percentile, standard_deviation, interquartile, gradient]
  percentile: [10, 30, 50, 70, 90]
  standard_deviation: [1, 1.5, 2, 2.5, 3]
  interquartile: [0.5, 0.75, 1, 1.25, 1.5]
  gradient: [10, 30, 50, 70, 90]

AbsoluteLangchainChunker:
  breakpoint_threshold_type: [distance, gradient]
  distance: [0.1, 0.2, 0.3, 0.4, 0.5]
  gradient: [0.01, 0.05, 0.1, 0.15, 0.2]